(package "sideline"
         "0.1.1"
         "Show information on the side")

(website-url "https://github.com/emacs-sideline/sideline")
(keywords "convenience")

(package-file "sideline.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "27.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
